import os
from pathlib import Path

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import AppendEnvironmentVariable, DeclareLaunchArgument, IncludeLaunchDescription, OpaqueFunction, SetEnvironmentVariable
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


ROBOTS = [
    {'name': 'robot1', 'x': '-5.5', 'y': '-1.0', 'yaw': '0.0'},
    {'name': 'robot2', 'x': '-5.5', 'y': '1.0', 'yaw': '0.0'},
]


def patch_between(text, old, new):
    if old not in text:
        raise RuntimeError(f'Missing expected SDF snippet: {old}')
    return text.replace(old, new)


def make_robot_sdf(base_sdf, robot_name):
    text = base_sdf
    replacements = {
        '<topic>imu</topic>': f'<topic>/{robot_name}/imu</topic>',
        '<topic>scan</topic>': f'<topic>/{robot_name}/scan</topic>',
        '<gz_frame_id>base_scan</gz_frame_id>': f'<gz_frame_id>{robot_name}/base_scan</gz_frame_id>',
        '<topic>camera/image_raw</topic>': f'<topic>/{robot_name}/camera/image_raw</topic>',
        '<gz_frame_id>camera_rgb_frame</gz_frame_id>': f'<gz_frame_id>{robot_name}/camera_rgb_frame</gz_frame_id>',
        '<topic>cmd_vel</topic>': f'<topic>/{robot_name}/cmd_vel</topic>',
        '<odom_topic>odom</odom_topic>': f'<odom_topic>/{robot_name}/odom</odom_topic>',
        '<frame_id>odom</frame_id>': f'<frame_id>{robot_name}/odom</frame_id>',
        '<child_frame_id>base_footprint</child_frame_id>': f'<child_frame_id>{robot_name}/base_footprint</child_frame_id>',
        '<tf_topic>/tf</tf_topic>': f'<tf_topic>/{robot_name}/tf</tf_topic>',
        '<topic>joint_states</topic>': f'<topic>/{robot_name}/joint_states</topic>',
    }
    for old, new in replacements.items():
        text = patch_between(text, old, new)
    return text


def make_bridge_yaml(robot_name):
    return f'''# Generated by multi_robot_world.launch.py for {robot_name}
- ros_topic_name: "/{robot_name}/joint_states"
  gz_topic_name: "/{robot_name}/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/{robot_name}/odom"
  gz_topic_name: "/{robot_name}/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/{robot_name}/tf"
  gz_topic_name: "/{robot_name}/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/{robot_name}/cmd_vel"
  gz_topic_name: "/{robot_name}/cmd_vel"
  ros_type_name: "geometry_msgs/msg/TwistStamped"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/{robot_name}/imu"
  gz_topic_name: "/{robot_name}/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/{robot_name}/scan"
  gz_topic_name: "/{robot_name}/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
'''


def setup_multi_robot(context, *args, **kwargs):
    package_share = get_package_share_directory('warehouse_robot_sim')
    turtlebot3_share = get_package_share_directory('turtlebot3_gazebo')
    ros_gz_sim_share = get_package_share_directory('ros_gz_sim')

    model = LaunchConfiguration('model').perform(context)
    world_path = os.path.join(package_share, 'worlds', 'warehouse.world')
    gz_sim_launch = os.path.join(ros_gz_sim_share, 'launch', 'gz_sim.launch.py')
    model_folder = f'turtlebot3_{model}'
    base_sdf_path = os.path.join(turtlebot3_share, 'models', model_folder, 'model.sdf')
    urdf_path = os.path.join(turtlebot3_share, 'urdf', f'turtlebot3_{model}.urdf')

    tmp_dir = Path('/tmp/warehouse_robot_sim_multi')
    tmp_dir.mkdir(parents=True, exist_ok=True)
    clock_bridge_path = tmp_dir / 'clock_bridge.yaml'
    clock_bridge_path.write_text("""- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
""")
    base_sdf = Path(base_sdf_path).read_text()
    robot_desc = Path(urdf_path).read_text()

    actions = [
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(gz_sim_launch),
            launch_arguments={
                'gz_args': ['-r -s -v2 ', world_path],
                'on_exit_shutdown': 'true',
            }.items(),
        ),
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(gz_sim_launch),
            launch_arguments={'gz_args': '-g -v2 '}.items(),
        ),
        Node(
            package='ros_gz_bridge',
            executable='parameter_bridge',
            name='clock_bridge',
            arguments=['--ros-args', '-p', f'config_file:={clock_bridge_path}'],
            output='screen',
        ),
    ]

    for robot in ROBOTS:
        name = robot['name']
        sdf_path = tmp_dir / f'{name}.sdf'
        bridge_path = tmp_dir / f'{name}_bridge.yaml'
        sdf_path.write_text(make_robot_sdf(base_sdf, name))
        bridge_path.write_text(make_bridge_yaml(name))

        actions.extend([
            Node(
                package='robot_state_publisher',
                executable='robot_state_publisher',
                namespace=name,
                name='robot_state_publisher',
                output='screen',
                parameters=[{
                    'use_sim_time': True,
                    'robot_description': robot_desc,
                    'frame_prefix': f'{name}/',
                }],
                remappings=[
                    ('/tf', 'tf'),
                    ('/tf_static', 'tf_static'),
                ],
            ),
            Node(
                package='ros_gz_sim',
                executable='create',
                arguments=[
                    '-name', name,
                    '-file', str(sdf_path),
                    '-x', robot['x'],
                    '-y', robot['y'],
                    '-z', '0.01',
                    '-Y', robot['yaw'],
                ],
                output='screen',
            ),
            Node(
                package='ros_gz_bridge',
                executable='parameter_bridge',
                name=f'{name}_bridge',
                arguments=['--ros-args', '-p', f'config_file:={bridge_path}'],
                output='screen',
            ),
        ])

    return actions


def generate_launch_description():
    turtlebot3_share = get_package_share_directory('turtlebot3_gazebo')

    return LaunchDescription([
        DeclareLaunchArgument('model', default_value='waffle_pi'),
        SetEnvironmentVariable('TURTLEBOT3_MODEL', LaunchConfiguration('model')),
        AppendEnvironmentVariable(
            'GZ_SIM_RESOURCE_PATH',
            os.path.join(turtlebot3_share, 'models'),
        ),
        OpaqueFunction(function=setup_multi_robot),
    ])
